const AUTHENTICATION_STATE = {
	AUTHENTICATED: "AUTHENTICATED",
	UNAUTHENTICATED: "UNAUTHENTICATED",
	ACCESS_TOKEN_EXPIRED: "ACCESS_TOKEN_EXPIRED",
	REFRESH_TOKEN_EXPIRED: "REFRESH_TOKEN_EXPIRED",
};

export default AUTHENTICATION_STATE;
